### ISSUE TITLE
Add keyboard support

### ISSUE THREAD

**Issue by bryceosterhaus** [metal/metal-devtools#10]
Add keyboard support for navigating through component nodes

**Comment by bryceosterhaus** [comment]
https://github.com/metal/metal-devtools/commit/a528fa4c086db3b31005885a132b4862a5a9f125

**Comment by mthadley** [comment]
![7drhiqr](https://cloud.githubusercontent.com/assets/2635560/25640503/9b25caea-2f44-11e7-8d19-11354c221482.gif)
